### ISSUE TITLE
synonyms of HP_0000191 (Accessory oral frenulum)

### ISSUE THREAD

**Issue by drseb** [obophenotype/human-phenotype-ontology#3336]
#Supernumerary oral frenum 

question is frenum really a synonym of frenulum ?

**Comment by pnrobinson** [comment]
Frenum is a small frenulum
see
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3636930/
I think both are used occasionally but frenulum is much more common

**Comment by pnrobinson** [comment]
I have updated the comment. Frenum is OK. 
One issue is that the definition is wrong (frenula are not limited to the tongue

'has part' some 
    (morphology
     and ('inheres in' some 'frenulum of tongue')
     and ('has modifier' some abnormal))

In uberon there is frenulum of lip and frenulum of tongue. This class essentially refers to the union of these two kinds of frenula. Should we be adding a new uberon class for this @cmungall @drseb

**Comment by pnrobinson** [comment]
@drseb @cmungall -- should we leave things are they are for now? This is not a big inaccuracy, or is there some way of doing this now in uberon?

**Comment by cmungall** [comment]
you'll get incorrect inferences - what about using a Union construct for now, and then replace with the next uberon release?

**Comment by drseb** [comment]
We will forget it. Can we get auto-pinged, when it is in Uberon?

**Comment by cmungall** [comment]
Yes. I will post here when the release is made

**Comment by pnrobinson** [comment]
@cmungall is this ready? Is this "oral frenulum"?
https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0036293
In this case can we mireot etc? @drseb

**Comment by cmungall** [comment]
That is it, you can go ahead and include in import

**Comment by drseb** [comment]
done

**Comment by pnrobinson** [comment]
I still cannot seem to find 'oral frenulum' in the imports @drseb

**Comment by drseb** [comment]
God, I hope the new import strategy will soon be finished.... it is now in the imports.
